/**
 * PitfallDetector — 坑点检测模块
 *
 * 检测反模式（过长方法、过深嵌套、God Class 等）、
 * 识别 TODO/FIXME/HACK/XXX 标记注释、检测硬编码配置值、
 * 标注缺少测试的核心模块。
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { AnalysisModuleInterface, ModuleResult } from '../plugins/analysis-module.js';
import type { LanguagePlugin } from '../plugins/language-plugin.js';
import type {
  ProjectProfile,
  PitfallResult,
  PitfallRecord,
  PitfallCategory,
  AstNode,
  OpsConfig,
  Dependency,
  ModuleInfo,
} from '../models/index.js';

// ─── Default OpsConfig thresholds ───

const DEFAULT_CONFIG: OpsConfig = {
  antiPatternThresholds: {
    maxMethodLines: 80,
    maxNestingDepth: 4,
    maxClassMethods: 20,
    maxClassLines: 500,
    maxFileLines: 1000,
  },
  autoGeneratedDirs: ['build', 'dist', 'node_modules', 'target', '.gradle', '__pycache__'],
  maxTreeDepth: 5,
};

// ─── Regex patterns ───

const TODO_MARKER_RE = /\b(TODO|FIXME|HACK|XXX)\b/i;
const HARDCODED_URL_RE = /https?:\/\/[^\s'"`,)}\]]+/;
const HARDCODED_IP_RE = /\b(?:\d{1,3}\.){3}\d{1,3}\b/;
const HARDCODED_PORT_RE = /(?:port\s*[=:]\s*|:\s*)(\d{4,5})\b/i;
const HARDCODED_API_KEY_RE = /(?:api[_-]?key|secret|token|password|passwd)\s*[=:]\s*['"][^'"]{8,}['"]/i;

const SOURCE_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.py', '.pyw',
  '.go',
  '.java', '.kt', '.scala',
  '.rb', '.rs', '.c', '.cpp', '.h', '.hpp', '.cs',
]);


export class PitfallDetector implements AnalysisModuleInterface {
  private config: OpsConfig;

  constructor(config?: Partial<OpsConfig>) {
    this.config = {
      ...DEFAULT_CONFIG,
      ...config,
      antiPatternThresholds: {
        ...DEFAULT_CONFIG.antiPatternThresholds,
        ...config?.antiPatternThresholds,
      },
    };
  }

  getName(): string {
    return 'pitfall';
  }

  async analyze(profile: ProjectProfile, plugins: LanguagePlugin[]): Promise<ModuleResult> {
    const records: PitfallRecord[] = [];
    const root = profile.projectPath;

    // Collect AST nodes from all plugins
    const allNodes: AstNode[] = [];
    const sourceFiles = this.collectSourceFiles(root);

    for (const plugin of plugins) {
      for (const filePath of sourceFiles) {
        try {
          const nodes = plugin.parseFile(filePath);
          allNodes.push(...nodes);
        } catch {
          // Skip files that can't be parsed by this plugin
        }
      }
    }

    // 1. Anti-pattern detection from AST nodes
    records.push(...this.detectAntiPatterns(allNodes));

    // 2. Deprecated/vulnerable dependency detection
    const allDeps: Dependency[] = [];
    for (const plugin of plugins) {
      try {
        allDeps.push(...plugin.extractDependencies(root));
      } catch {
        // Skip
      }
    }
    records.push(...this.detectDeprecatedDependencies(allDeps));

    // 3. TODO/FIXME/HACK/XXX markers (regex-based scan)
    records.push(...this.detectTodoMarkers(root, sourceFiles));

    // 4. Hardcoded config values (regex-based scan)
    records.push(...this.detectHardcodedConfigs(root, sourceFiles));

    // 5. Missing tests
    const allModules: ModuleInfo[] = [];
    for (const plugin of plugins) {
      try {
        allModules.push(...plugin.identifyModules(root));
      } catch {
        // Skip
      }
    }
    records.push(...this.detectMissingTests(root, allModules, sourceFiles));

    // Build summary
    const summary = this.buildSummary(records);

    const result: PitfallResult = { records, summary };
    return result;
  }

  // ─── Anti-pattern detection ───

  detectAntiPatterns(nodes: AstNode[]): PitfallRecord[] {
    const records: PitfallRecord[] = [];
    const thresholds = this.config.antiPatternThresholds;

    for (const node of nodes) {
      // Long methods
      if (node.type === 'method' || node.type === 'function' || node.type === 'constructor') {
        const lines = node.endLine - node.startLine;
        if (lines > thresholds.maxMethodLines) {
          records.push({
            category: 'anti-pattern',
            severity: 'medium',
            filePath: node.filePath,
            line: node.startLine,
            description: `方法 '${node.name}' 有 ${lines} 行（阈值: ${thresholds.maxMethodLines}）`,
            suggestion: '建议将此方法拆分为更小的、职责单一的方法。',
          });
        }
      }

      // God Class: too many methods or too many lines
      if (node.type === 'class') {
        const methodCount = node.children.filter(
          c => c.type === 'method' || c.type === 'constructor',
        ).length;
        const classLines = node.endLine - node.startLine;

        if (methodCount > thresholds.maxClassMethods) {
          records.push({
            category: 'anti-pattern',
            severity: 'high',
            filePath: node.filePath,
            line: node.startLine,
            description: `类 '${node.name}' 有 ${methodCount} 个方法（阈值: ${thresholds.maxClassMethods}）`,
            suggestion: '建议按单一职责原则拆分此类。',
          });
        }

        if (classLines > thresholds.maxClassLines) {
          records.push({
            category: 'anti-pattern',
            severity: 'high',
            filePath: node.filePath,
            line: node.startLine,
            description: `类 '${node.name}' 有 ${classLines} 行（阈值: ${thresholds.maxClassLines}）`,
            suggestion: '建议将功能提取到独立的类中。',
          });
        }
      }

      // Deep nesting (approximate from AST children depth)
      if (node.type === 'method' || node.type === 'function') {
        const maxDepth = this.measureNestingDepth(node);
        if (maxDepth > thresholds.maxNestingDepth) {
          records.push({
            category: 'anti-pattern',
            severity: 'medium',
            filePath: node.filePath,
            line: node.startLine,
            description: `方法 '${node.name}' 嵌套深度为 ${maxDepth}（阈值: ${thresholds.maxNestingDepth}）`,
            suggestion: '建议使用提前返回、守卫子句或提取嵌套逻辑。',
          });
        }
      }

      // Recurse into children
      if (node.children.length > 0) {
        records.push(...this.detectAntiPatterns(node.children));
      }
    }

    return records;
  }

  // ─── Long file detection (called separately with source file list) ───

  detectLongFiles(sourceFiles: string[]): PitfallRecord[] {
    const records: PitfallRecord[] = [];
    const maxLines = this.config.antiPatternThresholds.maxFileLines;

    for (const filePath of sourceFiles) {
      try {
        const content = fs.readFileSync(filePath, 'utf-8');
        const lineCount = content.split('\n').length;
        if (lineCount > maxLines) {
          records.push({
            category: 'anti-pattern',
            severity: 'low',
            filePath,
            description: `文件有 ${lineCount} 行（阈值: ${maxLines}）`,
            suggestion: '建议将此文件拆分为更小的模块。',
          });
        }
      } catch {
        // Skip unreadable files
      }
    }

    return records;
  }

  // ─── Deprecated/vulnerable dependency detection ───

  detectDeprecatedDependencies(dependencies: Dependency[]): PitfallRecord[] {
    const records: PitfallRecord[] = [];

    // Known deprecated/vulnerable packages (simplified heuristic)
    const KNOWN_DEPRECATED: Record<string, { reason: string; alternative: string }> = {
      request: { reason: '自 2020 年起已废弃', alternative: '建议使用 node-fetch、axios 或 got' },
      'node-uuid': { reason: '已废弃', alternative: '建议使用 uuid 包' },
      nomnom: { reason: '已废弃', alternative: '建议使用 commander 或 yargs' },
      'coffee-script': { reason: '已废弃', alternative: '建议使用 CoffeeScript (coffeescript)' },
      tsd: { reason: '已废弃', alternative: '建议使用 @types 包' },
      'istanbul': { reason: '已废弃', alternative: '建议使用 nyc 或 c8' },
      'jade': { reason: '已更名', alternative: '建议使用 pug' },
      'github': { reason: '已废弃', alternative: '建议使用 @octokit/rest' },
      'natives': { reason: '已废弃且存在安全风险', alternative: '建议移除此依赖' },
      'left-pad': { reason: '不必要', alternative: '建议使用 String.prototype.padStart()' },
    };

    for (const dep of dependencies) {
      const known = KNOWN_DEPRECATED[dep.name];
      if (known) {
        records.push({
          category: 'deprecated-dep',
          severity: 'medium',
          filePath: 'package.json',
          description: `依赖 '${dep.name}@${dep.version}' 已废弃: ${known.reason}`,
          suggestion: known.alternative,
        });
      }
    }

    return records;
  }

  // ─── TODO/FIXME/HACK/XXX marker detection ───

  detectTodoMarkers(root: string, sourceFiles: string[]): PitfallRecord[] {
    const records: PitfallRecord[] = [];

    for (const filePath of sourceFiles) {
      try {
        const content = fs.readFileSync(filePath, 'utf-8');
        const lines = content.split('\n');

        for (let i = 0; i < lines.length; i++) {
          const line = lines[i];
          const match = line.match(TODO_MARKER_RE);
          if (match) {
            const marker = match[1].toUpperCase();
            const severity = (marker === 'FIXME' || marker === 'HACK') ? 'medium' : 'low';
            const relPath = path.relative(root, filePath);

            records.push({
              category: 'todo-marker',
              severity,
              filePath: relPath,
              line: i + 1,
              description: `${marker} 标记发现: ${line.trim().substring(0, 120)}`,
              suggestion: `请处理此 ${marker} 注释或创建跟踪问题。`,
            });
          }
        }
      } catch {
        // Skip unreadable files
      }
    }

    return records;
  }

  // ─── Hardcoded config detection ───

  detectHardcodedConfigs(root: string, sourceFiles: string[]): PitfallRecord[] {
    const records: PitfallRecord[] = [];

    for (const filePath of sourceFiles) {
      try {
        const content = fs.readFileSync(filePath, 'utf-8');
        const lines = content.split('\n');
        const relPath = path.relative(root, filePath);

        // Skip test files and config files
        if (this.isTestFile(filePath) || this.isConfigFile(filePath)) continue;

        for (let i = 0; i < lines.length; i++) {
          const line = lines[i];

          // Skip comments
          const trimmed = line.trim();
          if (trimmed.startsWith('//') || trimmed.startsWith('#') || trimmed.startsWith('*')) continue;

          // Hardcoded URLs
          if (HARDCODED_URL_RE.test(line) && !this.isImportLine(line)) {
            records.push({
              category: 'hardcoded-config',
              severity: 'medium',
              filePath: relPath,
              line: i + 1,
              description: `检测到硬编码 URL: ${line.trim().substring(0, 120)}`,
              suggestion: '建议将 URL 移至配置文件或环境变量。',
            });
          }

          // Hardcoded IP addresses
          if (HARDCODED_IP_RE.test(line) && !this.isLoopbackOrLocalhost(line)) {
            records.push({
              category: 'hardcoded-config',
              severity: 'medium',
              filePath: relPath,
              line: i + 1,
              description: `检测到硬编码 IP 地址: ${line.trim().substring(0, 120)}`,
              suggestion: '建议将 IP 地址移至配置文件或环境变量。',
            });
          }

          // Hardcoded API keys / secrets
          if (HARDCODED_API_KEY_RE.test(line)) {
            records.push({
              category: 'hardcoded-config',
              severity: 'medium',
              filePath: relPath,
              line: i + 1,
              description: `检测到可能的硬编码密钥: ${line.trim().substring(0, 120)}`,
              suggestion: '建议将密钥移至环境变量或密钥管理器。',
            });
          }
        }
      } catch {
        // Skip unreadable files
      }
    }

    return records;
  }

  // ─── Missing test detection ───

  detectMissingTests(root: string, modules: ModuleInfo[], sourceFiles: string[]): PitfallRecord[] {
    const records: PitfallRecord[] = [];

    // Build a set of test file base names
    const testFiles = new Set<string>();
    for (const f of sourceFiles) {
      const base = path.basename(f);
      if (this.isTestFile(f)) {
        // Normalize: remove .test., .spec., _test., _spec. to get the module name
        const normalized = base
          .replace(/\.(test|spec)\./i, '.')
          .replace(/_(test|spec)\./i, '.')
          .replace(/Test\./i, '.')
          .toLowerCase();
        testFiles.add(normalized);
      }
    }

    for (const mod of modules) {
      const hasTest = mod.keyFiles.some(kf => {
        const base = path.basename(kf).toLowerCase();
        return testFiles.has(base);
      });

      if (!hasTest) {
        records.push({
          category: 'missing-test',
          severity: 'low',
          filePath: mod.path,
          description: `模块 '${mod.name}' 没有对应的测试文件`,
          suggestion: '建议为此模块添加单元测试以提高代码可靠性。',
        });
      }
    }

    return records;
  }

  // ─── Helpers ───

  private measureNestingDepth(node: AstNode): number {
    if (node.children.length === 0) return 0;
    let maxChildDepth = 0;
    for (const child of node.children) {
      const childDepth = this.measureNestingDepth(child);
      if (childDepth > maxChildDepth) maxChildDepth = childDepth;
    }
    return 1 + maxChildDepth;
  }

  private collectSourceFiles(root: string): string[] {
    const files: string[] = [];
    const autoGenDirs = new Set(this.config.autoGeneratedDirs);

    const walk = (dir: string) => {
      let entries: fs.Dirent[];
      try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
      } catch {
        return;
      }

      for (const entry of entries) {
        if (entry.name.startsWith('.')) continue;
        const fullPath = path.join(dir, entry.name);

        if (entry.isDirectory()) {
          if (!autoGenDirs.has(entry.name)) {
            walk(fullPath);
          }
        } else if (entry.isFile()) {
          const ext = path.extname(entry.name).toLowerCase();
          if (SOURCE_EXTENSIONS.has(ext)) {
            files.push(fullPath);
          }
        }
      }
    };

    walk(root);
    return files;
  }

  private isTestFile(filePath: string): boolean {
    const base = path.basename(filePath).toLowerCase();
    return (
      base.includes('.test.') ||
      base.includes('.spec.') ||
      base.includes('_test.') ||
      base.includes('_spec.') ||
      base.endsWith('test.ts') ||
      base.endsWith('test.js') ||
      base.endsWith('test.py') ||
      base.endsWith('_test.go')
    );
  }

  private isConfigFile(filePath: string): boolean {
    const base = path.basename(filePath).toLowerCase();
    return (
      base.endsWith('.config.ts') ||
      base.endsWith('.config.js') ||
      base === 'config.ts' ||
      base === 'config.js' ||
      base === 'config.py' ||
      base.endsWith('.env') ||
      base.endsWith('.yml') ||
      base.endsWith('.yaml') ||
      base.endsWith('.json')
    );
  }

  private isImportLine(line: string): boolean {
    const trimmed = line.trim();
    return (
      trimmed.startsWith('import ') ||
      trimmed.startsWith('from ') ||
      trimmed.startsWith('require(') ||
      trimmed.includes('require(')
    );
  }

  private isLoopbackOrLocalhost(line: string): boolean {
    return /127\.0\.0\.1|0\.0\.0\.0/.test(line);
  }

  private buildSummary(records: PitfallRecord[]): PitfallResult['summary'] {
    const byCategory: Record<PitfallCategory, number> = {
      'anti-pattern': 0,
      'deprecated-dep': 0,
      'security-risk': 0,
      'todo-marker': 0,
      'code-style': 0,
      'hardcoded-config': 0,
      'missing-test': 0,
    };

    const bySeverity: Record<'high' | 'medium' | 'low', number> = {
      high: 0,
      medium: 0,
      low: 0,
    };

    for (const r of records) {
      byCategory[r.category] = (byCategory[r.category] || 0) + 1;
      bySeverity[r.severity] = (bySeverity[r.severity] || 0) + 1;
    }

    return {
      total: records.length,
      byCategory,
      bySeverity,
    };
  }
}
