import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { StructureMapper } from './structure-mapper.js';
import type { ProjectProfile, DirectoryNode, StructureResult } from '../models/index.js';
import type { LanguagePlugin } from '../plugins/language-plugin.js';
import type { ModuleInfo } from '../models/module-info.js';

function makeProfile(projectPath: string, modules: ProjectProfile['modules'] = []): ProjectProfile {
  return {
    projectName: 'test-project',
    projectPath,
    primaryLanguage: 'typescript',
    languages: [{ language: 'typescript', fileCount: 10, lineCount: 500, percentage: 100 }],
    buildTool: 'npm',
    modules,
    fileStats: { totalFiles: 10, sourceFiles: 8, testFiles: 1, configFiles: 1, totalLines: 500 },
  };
}

function makePlugin(modules: ModuleInfo[] = []): LanguagePlugin {
  return {
    getLanguageId: () => 'typescript',
    parseFile: () => [],
    extractDependencies: () => [],
    identifyApis: () => [],
    identifyModules: () => modules,
  };
}

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'structure-mapper-test-'));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

/** Helper to create a directory structure from a spec object */
function createStructure(base: string, spec: Record<string, unknown>): void {
  for (const [name, value] of Object.entries(spec)) {
    const fullPath = path.join(base, name);
    if (typeof value === 'string') {
      fs.writeFileSync(fullPath, value);
    } else {
      fs.mkdirSync(fullPath, { recursive: true });
      createStructure(fullPath, value as Record<string, unknown>);
    }
  }
}

describe('StructureMapper', () => {
  const mapper = new StructureMapper();

  describe('getName', () => {
    it('returns "structure"', () => {
      expect(mapper.getName()).toBe('structure');
    });
  });

  describe('buildDirectoryTree', () => {
    it('builds a tree with correct file counts', () => {
      createStructure(tmpDir, {
        src: {
          'index.ts': 'export {}',
          'app.ts': 'console.log("hi")',
        },
        'package.json': '{}',
      });

      const tree = mapper.buildDirectoryTree(tmpDir);
      expect(tree.type).toBe('directory');
      expect(tree.fileCount).toBe(3);
      // src dir should have 2 files
      const srcNode = tree.children.find((c) => c.name === 'src');
      expect(srcNode).toBeDefined();
      expect(srcNode!.fileCount).toBe(2);
    });

    it('annotates known directories', () => {
      createStructure(tmpDir, {
        src: { 'a.ts': '' },
        test: { 'a.test.ts': '' },
        config: { 'app.json': '' },
        docs: { 'readme.md': '' },
      });

      const tree = mapper.buildDirectoryTree(tmpDir);
      const findChild = (name: string) => tree.children.find((c) => c.name === name);

      expect(findChild('src')!.annotation).toBe('源码目录');
      expect(findChild('test')!.annotation).toBe('测试目录');
      expect(findChild('config')!.annotation).toBe('配置目录');
      expect(findChild('docs')!.annotation).toBe('文档目录');
    });

    it('annotates known files', () => {
      createStructure(tmpDir, {
        'index.ts': '',
        'main.py': '',
        'package.json': '{}',
        'Dockerfile': '',
        'utils.ts': '',
      });

      const tree = mapper.buildDirectoryTree(tmpDir);
      const findChild = (name: string) => tree.children.find((c) => c.name === name);

      expect(findChild('index.ts')!.annotation).toBe('入口文件');
      expect(findChild('main.py')!.annotation).toBe('入口文件');
      expect(findChild('package.json')!.annotation).toBe('构建配置');
      expect(findChild('Dockerfile')!.annotation).toBe('容器配置');
      expect(findChild('utils.ts')!.annotation).toBeUndefined();
    });

    it('marks auto-generated directories as collapsed', () => {
      createStructure(tmpDir, {
        node_modules: { 'lodash': { 'index.js': '' } },
        dist: { 'bundle.js': '' },
        src: { 'app.ts': '' },
      });

      const tree = mapper.buildDirectoryTree(tmpDir);
      const nm = tree.children.find((c) => c.name === 'node_modules');
      const dist = tree.children.find((c) => c.name === 'dist');
      const src = tree.children.find((c) => c.name === 'src');

      expect(nm!.isAutoGenerated).toBe(true);
      expect(nm!.isCollapsed).toBe(true);
      expect(dist!.isAutoGenerated).toBe(true);
      expect(dist!.isCollapsed).toBe(true);
      expect(src!.isAutoGenerated).toBe(false);
      expect(src!.isCollapsed).toBe(false);
    });

    it('collapses directories deeper than maxDepth', () => {
      // Create a structure 7 levels deep
      createStructure(tmpDir, {
        a: { b: { c: { d: { e: { f: { 'deep.txt': 'content' } } } } } },
      });

      const tree = mapper.buildDirectoryTree(tmpDir, 3);
      // depth 0 = root, 1 = a, 2 = b, 3 = c (should be collapsed at depth >= 3)
      const a = tree.children.find((c) => c.name === 'a')!;
      expect(a.isCollapsed).toBe(false); // depth 1
      const b = a.children.find((c) => c.name === 'b')!;
      expect(b.isCollapsed).toBe(false); // depth 2
      const c = b.children.find((c) => c.name === 'c')!;
      expect(c.isCollapsed).toBe(true); // depth 3 >= maxDepth
      expect(c.children).toHaveLength(0); // collapsed, no children built
      expect(c.fileCount).toBe(1); // but file count is still correct
    });

    it('counts files in collapsed auto-generated directories', () => {
      createStructure(tmpDir, {
        node_modules: {
          'pkg-a': { 'index.js': '', 'utils.js': '' },
          'pkg-b': { 'index.js': '' },
        },
      });

      const tree = mapper.buildDirectoryTree(tmpDir);
      const nm = tree.children.find((c) => c.name === 'node_modules')!;
      expect(nm.fileCount).toBe(3);
      expect(nm.children).toHaveLength(0); // collapsed
    });

    it('sets correct depth values', () => {
      createStructure(tmpDir, {
        src: { lib: { 'util.ts': '' } },
      });

      const tree = mapper.buildDirectoryTree(tmpDir);
      expect(tree.depth).toBe(0);
      const src = tree.children.find((c) => c.name === 'src')!;
      expect(src.depth).toBe(1);
      const lib = src.children.find((c) => c.name === 'lib')!;
      expect(lib.depth).toBe(2);
      const util = lib.children.find((c) => c.name === 'util.ts')!;
      expect(util.depth).toBe(3);
    });
  });

  describe('buildModuleDiagram', () => {
    it('returns undefined when no plugins provide modules', () => {
      const plugin = makePlugin([]);
      const result = mapper.buildModuleDiagram([plugin], tmpDir);
      expect(result).toBeUndefined();
    });

    it('generates valid Mermaid graph from plugin modules', () => {
      const modules: ModuleInfo[] = [
        { name: 'auth', path: 'src/auth', description: '', isInferred: false, keyClasses: [], keyFiles: [], dependencies: ['db'] },
        { name: 'db', path: 'src/db', description: '', isInferred: false, keyClasses: [], keyFiles: [], dependencies: [] },
        { name: 'api', path: 'src/api', description: '', isInferred: false, keyClasses: [], keyFiles: [], dependencies: ['auth', 'db'] },
      ];
      const plugin = makePlugin(modules);
      const result = mapper.buildModuleDiagram([plugin], tmpDir);

      expect(result).toBeDefined();
      expect(result!.nodes).toEqual(['auth', 'db', 'api']);
      expect(result!.edges).toContainEqual({ from: 'auth', to: 'db' });
      expect(result!.edges).toContainEqual({ from: 'api', to: 'auth' });
      expect(result!.edges).toContainEqual({ from: 'api', to: 'db' });
      expect(result!.syntax).toContain('graph TD');
      expect(result!.syntax).toContain('auth["auth"]');
    });

    it('ignores dependencies to unknown modules', () => {
      const modules: ModuleInfo[] = [
        { name: 'core', path: 'src/core', description: '', isInferred: false, keyClasses: [], keyFiles: [], dependencies: ['external-lib'] },
      ];
      const plugin = makePlugin(modules);
      const result = mapper.buildModuleDiagram([plugin], tmpDir);

      expect(result).toBeDefined();
      expect(result!.edges).toHaveLength(0);
    });
  });

  describe('buildSubModuleDependencyDiagram', () => {
    it('returns undefined when fewer than 2 sub-modules', () => {
      const profile = makeProfile(tmpDir, [
        { name: 'only-one', path: 'only-one', language: 'typescript', buildTool: 'npm' },
      ]);
      const result = mapper.buildSubModuleDependencyDiagram(profile);
      expect(result).toBeUndefined();
    });

    it('generates diagram for npm sub-modules with dependencies', () => {
      // Create two sub-modules where module-a depends on module-b
      createStructure(tmpDir, {
        'module-a': {
          'package.json': JSON.stringify({ name: 'module-a', dependencies: { 'module-b': '^1.0.0' } }),
        },
        'module-b': {
          'package.json': JSON.stringify({ name: 'module-b' }),
        },
      });

      const profile = makeProfile(tmpDir, [
        { name: 'module-a', path: 'module-a', language: 'typescript', buildTool: 'npm' },
        { name: 'module-b', path: 'module-b', language: 'typescript', buildTool: 'npm' },
      ]);

      const result = mapper.buildSubModuleDependencyDiagram(profile);
      expect(result).toBeDefined();
      expect(result!.nodes).toEqual(['module-a', 'module-b']);
      expect(result!.edges).toContainEqual({ from: 'module-a', to: 'module-b', label: 'compile' });
      expect(result!.syntax).toContain('graph TD');
    });

    it('generates diagram with no edges when sub-modules are independent', () => {
      createStructure(tmpDir, {
        'mod-a': { 'package.json': JSON.stringify({ name: 'mod-a' }) },
        'mod-b': { 'package.json': JSON.stringify({ name: 'mod-b' }) },
      });

      const profile = makeProfile(tmpDir, [
        { name: 'mod-a', path: 'mod-a', language: 'typescript', buildTool: 'npm' },
        { name: 'mod-b', path: 'mod-b', language: 'typescript', buildTool: 'npm' },
      ]);

      const result = mapper.buildSubModuleDependencyDiagram(profile);
      expect(result).toBeDefined();
      expect(result!.edges).toHaveLength(0);
    });
  });

  describe('analyze (integration)', () => {
    it('returns a StructureResult with directoryTree', async () => {
      createStructure(tmpDir, {
        src: { 'index.ts': '' },
        'package.json': '{}',
      });

      const profile = makeProfile(tmpDir);
      const result = (await mapper.analyze(profile, [])) as StructureResult;

      expect(result.directoryTree).toBeDefined();
      expect(result.directoryTree.type).toBe('directory');
      expect(result.directoryTree.fileCount).toBe(2);
      expect(result.moduleDiagram).toBeUndefined();
      expect(result.subModuleDependencies).toBeUndefined();
    });
  });
});
