/**
 * StructureMapper — 项目结构地图分析模块
 *
 * 生成目录树结构图（含文件数量统计和功能标注）、
 * 模块关系图和子模块依赖关系图的 Mermaid 格式描述。
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type {
  ProjectProfile,
  StructureResult,
  DirectoryNode,
  MermaidGraph,
  ModuleInfo,
} from '../models/index.js';
import type { AnalysisModuleInterface, ModuleResult } from '../plugins/analysis-module.js';
import type { LanguagePlugin } from '../plugins/language-plugin.js';

/** Default max tree depth before collapsing */
const DEFAULT_MAX_DEPTH = 5;

/** Known auto-generated directory names */
const AUTO_GENERATED_DIRS = new Set([
  'build', 'dist', 'node_modules', 'target',
  '.gradle', '__pycache__', 'out', '.next', '.nuxt', 'coverage',
]);

/** Directory annotation rules: directory name → annotation */
const DIR_ANNOTATIONS: Record<string, string> = {
  src: '源码目录',
  lib: '源码目录',
  app: '源码目录',
  test: '测试目录',
  tests: '测试目录',
  __tests__: '测试目录',
  config: '配置目录',
  configs: '配置目录',
  '.config': '配置目录',
  docs: '文档目录',
  doc: '文档目录',
};

/** File annotation rules: base filename pattern → annotation */
const FILE_ANNOTATIONS: Record<string, string> = {
  'package.json': '构建配置',
  'pom.xml': '构建配置',
  'go.mod': '构建配置',
  'Dockerfile': '容器配置',
  'docker-compose.yml': '容器配置',
  'docker-compose.yaml': '容器配置',
};

/** File name prefixes that indicate entry files */
const ENTRY_FILE_PREFIXES = ['main', 'index', 'app'];

/**
 * Get annotation for a file based on its name.
 */
function getFileAnnotation(fileName: string): string | undefined {
  // Check exact match first
  if (FILE_ANNOTATIONS[fileName]) {
    return FILE_ANNOTATIONS[fileName];
  }
  // Check entry file prefixes (main.*, index.*, app.*)
  const baseName = fileName.split('.')[0];
  if (ENTRY_FILE_PREFIXES.includes(baseName)) {
    return '入口文件';
  }
  return undefined;
}

/**
 * Get annotation for a directory based on its name.
 */
function getDirAnnotation(dirName: string): string | undefined {
  return DIR_ANNOTATIONS[dirName];
}

export class StructureMapper implements AnalysisModuleInterface {
  getName(): string {
    return 'structure';
  }

  async analyze(profile: ProjectProfile, plugins: LanguagePlugin[]): Promise<ModuleResult> {
    const directoryTree = this.buildDirectoryTree(profile.projectPath, DEFAULT_MAX_DEPTH);
    const moduleDiagram = this.buildModuleDiagram(plugins, profile.projectPath);
    const subModuleDependencies = this.buildSubModuleDependencyDiagram(profile);

    const result: StructureResult = {
      directoryTree,
      moduleDiagram,
      subModuleDependencies,
    };
    return result;
  }

  /**
   * Build a DirectoryNode tree from the project directory.
   */
  buildDirectoryTree(projectPath: string, maxDepth: number = DEFAULT_MAX_DEPTH): DirectoryNode {
    return this.buildNode(projectPath, path.basename(projectPath), '', 0, maxDepth);
  }

  private buildNode(
    absPath: string,
    name: string,
    relativePath: string,
    depth: number,
    maxDepth: number,
  ): DirectoryNode {
    const isDir = this.isDirectory(absPath);

    if (!isDir) {
      // File node
      return {
        name,
        path: relativePath,
        type: 'file',
        children: [],
        fileCount: 1,
        annotation: getFileAnnotation(name),
        isCollapsed: false,
        isAutoGenerated: false,
        depth,
      };
    }

    // Directory node
    const isAutoGen = AUTO_GENERATED_DIRS.has(name);
    const shouldCollapse = isAutoGen || depth >= maxDepth;

    const node: DirectoryNode = {
      name,
      path: relativePath,
      type: 'directory',
      children: [],
      fileCount: 0,
      annotation: getDirAnnotation(name),
      isCollapsed: shouldCollapse,
      isAutoGenerated: isAutoGen,
      depth,
    };

    if (shouldCollapse) {
      // Count files without building full subtree
      node.fileCount = this.countFiles(absPath);
      return node;
    }

    // Build children
    let entries: string[];
    try {
      entries = fs.readdirSync(absPath).sort();
    } catch {
      return node;
    }

    for (const entry of entries) {
      const childAbsPath = path.join(absPath, entry);
      const childRelPath = relativePath ? `${relativePath}/${entry}` : entry;
      const child = this.buildNode(childAbsPath, entry, childRelPath, depth + 1, maxDepth);
      node.children.push(child);
    }

    // fileCount = sum of all children's fileCounts
    node.fileCount = node.children.reduce((sum, c) => sum + c.fileCount, 0);

    return node;
  }

  /**
   * Count total files recursively in a directory (used for collapsed dirs).
   */
  private countFiles(dirPath: string): number {
    let count = 0;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dirPath, { withFileTypes: true });
    } catch {
      return 0;
    }
    for (const entry of entries) {
      if (entry.isDirectory()) {
        count += this.countFiles(path.join(dirPath, entry.name));
      } else {
        count += 1;
      }
    }
    return count;
  }

  private isDirectory(p: string): boolean {
    try {
      return fs.statSync(p).isDirectory();
    } catch {
      return false;
    }
  }

  /**
   * Build module relationship Mermaid diagram from plugins' identifyModules().
   */
  buildModuleDiagram(
    plugins: LanguagePlugin[],
    projectRoot: string,
  ): MermaidGraph | undefined {
    const allModules: ModuleInfo[] = [];
    for (const plugin of plugins) {
      const modules = plugin.identifyModules(projectRoot);
      allModules.push(...modules);
    }

    if (allModules.length === 0) {
      return undefined;
    }

    const nodes = allModules.map((m) => m.name);
    const edges: { from: string; to: string; label?: string }[] = [];

    for (const mod of allModules) {
      for (const dep of mod.dependencies) {
        // Only add edge if the dependency is a known module
        if (nodes.includes(dep)) {
          edges.push({ from: mod.name, to: dep });
        }
      }
    }

    const lines: string[] = ['graph TD'];
    for (const node of nodes) {
      const safeId = this.sanitizeMermaidId(node);
      lines.push(`  ${safeId}["${node}"]`);
    }
    for (const edge of edges) {
      const fromId = this.sanitizeMermaidId(edge.from);
      const toId = this.sanitizeMermaidId(edge.to);
      lines.push(`  ${fromId} --> ${toId}`);
    }

    return {
      syntax: lines.join('\n'),
      nodes,
      edges,
    };
  }

  /**
   * Build sub-module dependency Mermaid diagram from profile.modules.
   */
  buildSubModuleDependencyDiagram(profile: ProjectProfile): MermaidGraph | undefined {
    const subModules = profile.modules;
    if (!subModules || subModules.length < 2) {
      return undefined;
    }

    const nodes = subModules.map((m) => m.name);
    const edges: { from: string; to: string; label?: string }[] = [];

    for (const mod of subModules) {
      const modAbsPath = path.isAbsolute(mod.path)
        ? mod.path
        : path.join(profile.projectPath, mod.path);

      const deps = this.detectSubModuleDependencies(mod, subModules, modAbsPath);
      edges.push(...deps);
    }

    if (edges.length === 0 && nodes.length < 2) {
      return undefined;
    }

    const lines: string[] = ['graph TD'];
    for (const node of nodes) {
      const safeId = this.sanitizeMermaidId(node);
      lines.push(`  ${safeId}["${node}"]`);
    }
    for (const edge of edges) {
      const fromId = this.sanitizeMermaidId(edge.from);
      const toId = this.sanitizeMermaidId(edge.to);
      if (edge.label) {
        lines.push(`  ${fromId} -->|"${edge.label}"| ${toId}`);
      } else {
        lines.push(`  ${fromId} --> ${toId}`);
      }
    }

    return {
      syntax: lines.join('\n'),
      nodes,
      edges,
    };
  }

  /**
   * Detect dependencies between sub-modules by reading build config files.
   */
  private detectSubModuleDependencies(
    mod: { name: string; path: string; buildTool: string },
    allModules: { name: string; path: string; buildTool: string }[],
    modAbsPath: string,
  ): { from: string; to: string; label?: string }[] {
    const edges: { from: string; to: string; label?: string }[] = [];
    const others = allModules.filter((m) => m.name !== mod.name);
    if (others.length === 0) return edges;

    if (mod.buildTool === 'npm' || mod.buildTool === 'yarn' || mod.buildTool === 'pnpm') {
      const pkgPath = path.join(modAbsPath, 'package.json');
      let pkgJson: Record<string, unknown>;
      try {
        pkgJson = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
      } catch {
        return edges;
      }
      const sections = [
        { key: 'dependencies', label: 'compile' },
        { key: 'devDependencies', label: 'test' },
        { key: 'peerDependencies', label: 'runtime' },
      ];
      for (const { key, label } of sections) {
        const deps = pkgJson[key] as Record<string, string> | undefined;
        if (!deps) continue;
        const depNames = Object.keys(deps);
        for (const other of others) {
          if (depNames.includes(other.name)) {
            edges.push({ from: mod.name, to: other.name, label });
          }
        }
      }
    } else if (mod.buildTool === 'go-mod') {
      const goModPath = path.join(modAbsPath, 'go.mod');
      let content: string;
      try {
        content = fs.readFileSync(goModPath, 'utf-8');
      } catch {
        return edges;
      }
      for (const other of others) {
        if (content.includes(other.name)) {
          edges.push({ from: mod.name, to: other.name, label: 'compile' });
        }
      }
    } else if (mod.buildTool === 'maven' || mod.buildTool === 'gradle') {
      // For Maven/Gradle, check pom.xml or build.gradle for references
      const pomPath = path.join(modAbsPath, 'pom.xml');
      const gradlePath = path.join(modAbsPath, 'build.gradle');
      let content = '';
      try {
        content = fs.readFileSync(pomPath, 'utf-8');
      } catch {
        try {
          content = fs.readFileSync(gradlePath, 'utf-8');
        } catch {
          return edges;
        }
      }
      for (const other of others) {
        if (content.includes(other.name)) {
          edges.push({ from: mod.name, to: other.name, label: 'compile' });
        }
      }
    }

    return edges;
  }

  /**
   * Sanitize a name for use as a Mermaid node ID.
   */
  private sanitizeMermaidId(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_');
  }
}
