package com.analyzer.module;

import com.analyzer.model.*;
import com.analyzer.model.AnalysisReport.*;
import com.analyzer.plugin.AnalysisModuleInterface;
import com.analyzer.plugin.LanguagePlugin;

import java.io.IOException;
import java.nio.file.*;
import java.util.*;

public class StructureMapper implements AnalysisModuleInterface {

    private static final int DEFAULT_MAX_DEPTH = 5;
    private static final Set<String> AUTO_GENERATED_DIRS = Set.of(
            "build", "dist", "node_modules", "target", ".gradle",
            "__pycache__", "out", ".next", ".nuxt", "coverage"
    );
    private static final Map<String, String> DIR_ANNOTATIONS = Map.ofEntries(
            Map.entry("src", "源码目录"), Map.entry("lib", "源码目录"), Map.entry("app", "源码目录"),
            Map.entry("test", "测试目录"), Map.entry("tests", "测试目录"), Map.entry("__tests__", "测试目录"),
            Map.entry("config", "配置目录"), Map.entry("configs", "配置目录"),
            Map.entry("docs", "文档目录"), Map.entry("doc", "文档目录")
    );
    private static final Map<String, String> FILE_ANNOTATIONS = Map.of(
            "package.json", "构建配置", "pom.xml", "构建配置", "go.mod", "构建配置",
            "Dockerfile", "容器配置", "docker-compose.yml", "容器配置", "docker-compose.yaml", "容器配置"
    );
    private static final Set<String> ENTRY_FILE_PREFIXES = Set.of("main", "index", "app");

    @Override
    public String getName() { return "structure"; }

    @Override
    public Object analyze(ProjectProfile profile, List<LanguagePlugin> plugins) {
        DirectoryNode tree = buildDirectoryTree(profile.getProjectPath(), DEFAULT_MAX_DEPTH);
        MermaidGraph moduleDiagram = buildModuleDiagram(plugins, profile.getProjectPath());
        MermaidGraph subModuleDeps = buildSubModuleDependencyDiagram(profile);

        StructureResult result = new StructureResult();
        result.setDirectoryTree(tree);
        result.setModuleDiagram(moduleDiagram);
        result.setSubModuleDependencies(subModuleDeps);
        return result;
    }

    public DirectoryNode buildDirectoryTree(String projectPath, int maxDepth) {
        Path root = Path.of(projectPath);
        return buildNode(root, root.getFileName().toString(), "", 0, maxDepth);
    }

    private DirectoryNode buildNode(Path absPath, String name, String relPath, int depth, int maxDepth) {
        DirectoryNode node = new DirectoryNode();
        node.setName(name);
        node.setPath(relPath);
        node.setDepth(depth);
        node.setChildren(new ArrayList<>());

        if (!Files.isDirectory(absPath)) {
            node.setType("file");
            node.setFileCount(1);
            node.setAnnotation(getFileAnnotation(name));
            node.setCollapsed(false);
            node.setAutoGenerated(false);
            return node;
        }

        node.setType("directory");
        boolean isAutoGen = AUTO_GENERATED_DIRS.contains(name);
        boolean shouldCollapse = isAutoGen || depth >= maxDepth;
        node.setAutoGenerated(isAutoGen);
        node.setCollapsed(shouldCollapse);
        node.setAnnotation(DIR_ANNOTATIONS.get(name));

        if (shouldCollapse) {
            node.setFileCount(countFiles(absPath));
            return node;
        }

        try (DirectoryStream<Path> stream = Files.newDirectoryStream(absPath)) {
            List<Path> sorted = new ArrayList<>();
            stream.forEach(sorted::add);
            sorted.sort(Comparator.comparing(p -> p.getFileName().toString()));
            for (Path entry : sorted) {
                String childName = entry.getFileName().toString();
                String childRel = relPath.isEmpty() ? childName : relPath + "/" + childName;
                node.getChildren().add(buildNode(entry, childName, childRel, depth + 1, maxDepth));
            }
        } catch (IOException ignored) {}

        node.setFileCount(node.getChildren().stream().mapToInt(DirectoryNode::getFileCount).sum());
        return node;
    }

    private int countFiles(Path dir) {
        int count = 0;
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir)) {
            for (Path entry : stream) {
                if (Files.isDirectory(entry)) count += countFiles(entry);
                else count++;
            }
        } catch (IOException ignored) {}
        return count;
    }

    private String getFileAnnotation(String fileName) {
        if (FILE_ANNOTATIONS.containsKey(fileName)) return FILE_ANNOTATIONS.get(fileName);
        String baseName = fileName.contains(".") ? fileName.substring(0, fileName.indexOf('.')) : fileName;
        if (ENTRY_FILE_PREFIXES.contains(baseName)) return "入口文件";
        return null;
    }

    private MermaidGraph buildModuleDiagram(List<LanguagePlugin> plugins, String projectRoot) {
        List<ModuleInfo> allModules = new ArrayList<>();
        for (LanguagePlugin plugin : plugins) {
            allModules.addAll(plugin.identifyModules(Path.of(projectRoot)));
        }
        if (allModules.isEmpty()) return null;

        List<String> nodes = allModules.stream().map(ModuleInfo::getName).toList();
        List<MermaidGraph.MermaidEdge> edges = new ArrayList<>();
        StringBuilder sb = new StringBuilder("graph TD\n");
        for (String n : nodes) sb.append("  ").append(sanitize(n)).append("[\"").append(n).append("\"]\n");
        for (ModuleInfo mod : allModules) {
            if (mod.getDependencies() != null) {
                for (String dep : mod.getDependencies()) {
                    if (nodes.contains(dep)) {
                        edges.add(new MermaidGraph.MermaidEdge(mod.getName(), dep, null));
                        sb.append("  ").append(sanitize(mod.getName())).append(" --> ").append(sanitize(dep)).append("\n");
                    }
                }
            }
        }
        MermaidGraph g = new MermaidGraph();
        g.setSyntax(sb.toString().trim());
        g.setNodes(nodes);
        g.setEdges(edges);
        return g;
    }

    private MermaidGraph buildSubModuleDependencyDiagram(ProjectProfile profile) {
        var subs = profile.getModules();
        if (subs == null || subs.size() < 2) return null;
        List<String> nodes = subs.stream().map(ProjectProfile.SubModule::getName).toList();
        List<MermaidGraph.MermaidEdge> edges = new ArrayList<>();
        StringBuilder sb = new StringBuilder("graph TD\n");
        for (String n : nodes) sb.append("  ").append(sanitize(n)).append("[\"").append(n).append("\"]\n");

        MermaidGraph g = new MermaidGraph();
        g.setSyntax(sb.toString().trim());
        g.setNodes(nodes);
        g.setEdges(edges);
        return g;
    }

    private String sanitize(String name) { return name.replaceAll("[^a-zA-Z0-9_]", "_"); }
}
