package com.analyzer.model;

import java.util.List;

/**
 * OpsConfig — Ops 分析配置数据模型
 */
public class OpsConfig {
    private AntiPatternThresholds antiPatternThresholds;
    private List<String> autoGeneratedDirs;
    private int maxTreeDepth;

    public OpsConfig() {
        this.antiPatternThresholds = new AntiPatternThresholds();
        this.autoGeneratedDirs = List.of("build", "dist", "node_modules", "target", ".gradle", "__pycache__");
        this.maxTreeDepth = 5;
    }

    public AntiPatternThresholds getAntiPatternThresholds() { return antiPatternThresholds; }
    public void setAntiPatternThresholds(AntiPatternThresholds antiPatternThresholds) {
        this.antiPatternThresholds = antiPatternThresholds;
    }

    public List<String> getAutoGeneratedDirs() { return autoGeneratedDirs; }
    public void setAutoGeneratedDirs(List<String> autoGeneratedDirs) {
        this.autoGeneratedDirs = autoGeneratedDirs;
    }

    public int getMaxTreeDepth() { return maxTreeDepth; }
    public void setMaxTreeDepth(int maxTreeDepth) { this.maxTreeDepth = maxTreeDepth; }

    public static class AntiPatternThresholds {
        private int maxMethodLines;
        private int maxNestingDepth;
        private int maxClassMethods;
        private int maxClassLines;
        private int maxFileLines;

        public AntiPatternThresholds() {
            this.maxMethodLines = 80;
            this.maxNestingDepth = 4;
            this.maxClassMethods = 20;
            this.maxClassLines = 500;
            this.maxFileLines = 1000;
        }

        public int getMaxMethodLines() { return maxMethodLines; }
        public void setMaxMethodLines(int maxMethodLines) { this.maxMethodLines = maxMethodLines; }

        public int getMaxNestingDepth() { return maxNestingDepth; }
        public void setMaxNestingDepth(int maxNestingDepth) { this.maxNestingDepth = maxNestingDepth; }

        public int getMaxClassMethods() { return maxClassMethods; }
        public void setMaxClassMethods(int maxClassMethods) { this.maxClassMethods = maxClassMethods; }

        public int getMaxClassLines() { return maxClassLines; }
        public void setMaxClassLines(int maxClassLines) { this.maxClassLines = maxClassLines; }

        public int getMaxFileLines() { return maxFileLines; }
        public void setMaxFileLines(int maxFileLines) { this.maxFileLines = maxFileLines; }
    }
}
