/**
 * AnalysisReport — 分析报告及所有子结果数据模型
 */

import type { ProjectProfile } from './project-profile.js';
import type { Dependency, DependencyCategory } from './dependency.js';
import type { ApiEndpoint, HttpMethod } from './api-endpoint.js';
import type { ModuleInfo } from './module-info.js';
import type { EntryPoint, FlowTrace } from './flow-trace.js';
import type { PitfallRecord, PitfallCategory } from './pitfall-record.js';
import type { AiMemoryData } from './ai-memory.js';
import type { OpsConfig } from './ops-config.js';

// ─── AnalysisReport ───

export interface AnalysisReport {
  metadata: ReportMetadata;
  profile: ProjectProfile;
  architecture?: ArchitectureResult;
  business?: BusinessResult;
  flows?: FlowResult;
  apis?: ApiResult;
  structure?: StructureResult;
  ops?: OpsResult;
  pitfalls?: PitfallResult;
  quickstart?: QuickstartResult;
  aiMemory?: AiMemoryResult;
}

export interface ReportMetadata {
  generatedAt: string;
  analyzerVersion: string;
  analyzerType: 'java' | 'ts';
  projectName: string;
}

// ─── ArchitectureResult ───

export interface ArchitectureResult {
  dependencies: Dependency[];
  dependencyGroups: Record<DependencyCategory, Dependency[]>;
  layers: LayerInfo[];
  frameworks: FrameworkInfo[];
  moduleDependencyGraph?: MermaidGraph;
}

export interface LayerInfo {
  name: string;
  pattern: string;
  classes: string[];
  files: string[];
}

export interface FrameworkInfo {
  name: string;
  version?: string;
  category: string;
  evidence: string[];
}

export interface MermaidGraph {
  syntax: string;
  nodes: string[];
  edges: { from: string; to: string; label?: string }[];
}

// ─── BusinessResult ───

export interface BusinessResult {
  modules: ModuleInfo[];
  dataModels: DataModelInfo[];
}

export interface DataModelInfo {
  name: string;
  type: 'entity' | 'model' | 'dto' | 'vo' | 'other';
  filePath: string;
  fields: DataFieldInfo[];
  description?: string;
}

export interface DataFieldInfo {
  name: string;
  type: string;
  annotations: string[];
  description?: string;
}

// ─── FlowResult ───

export interface FlowResult {
  entryPoints: EntryPoint[];
  flows: FlowTrace[];
}

// ─── ApiResult ───

export interface ApiResult {
  endpoints: ApiEndpoint[];
  groups: ApiGroup[];
  totalCount: number;
}

export interface ApiGroup {
  name: string;
  basePath?: string;
  endpoints: ApiEndpoint[];
}

// ─── StructureResult ───

export interface StructureResult {
  directoryTree: DirectoryNode;
  moduleDiagram?: MermaidGraph;
  subModuleDependencies?: MermaidGraph;
}

export interface DirectoryNode {
  name: string;
  path: string;
  type: 'directory' | 'file';
  children: DirectoryNode[];
  fileCount: number;
  annotation?: string;
  isCollapsed: boolean;
  isAutoGenerated: boolean;
  depth: number;
}

// ─── OpsResult ───

export interface OpsResult {
  startup: StartupInfo[];
  containers?: ContainerConfig[];
  cicd?: CiCdPipeline[];
  configItems: ConfigItem[];
  externalServices: ExternalService[];
  envComparison?: EnvComparisonTable;
}

export interface StartupInfo {
  method: 'main-class' | 'script' | 'npm-script' | 'makefile' | 'other';
  command: string;
  description: string;
  filePath: string;
  isInferred: boolean;
}

export interface ContainerConfig {
  type: 'dockerfile' | 'docker-compose';
  filePath: string;
  baseImage?: string;
  ports: string[];
  volumes: string[];
  envVars: string[];
  services?: string[];
  description: string;
}

export interface CiCdPipeline {
  type: 'github-actions' | 'gitlab-ci' | 'jenkins' | 'other';
  filePath: string;
  stages: CiCdStage[];
  description: string;
}

export interface CiCdStage {
  name: string;
  steps: string[];
  triggers?: string[];
}

export interface ConfigItem {
  key: string;
  defaultValue?: string;
  description: string;
  required: boolean;
  source: string;
  environment?: string;
}

export interface ExternalService {
  name: string;
  type: 'database' | 'cache' | 'message-queue' | 'search-engine' | 'third-party-api' | 'other';
  evidence: string[];
  connectionConfig?: string;
}

export interface EnvComparisonTable {
  environments: string[];
  items: EnvComparisonItem[];
}

export interface EnvComparisonItem {
  key: string;
  values: Record<string, string | undefined>;
  isDifferent: boolean;
}

// ─── PitfallResult ───

export interface PitfallResult {
  records: PitfallRecord[];
  summary: {
    total: number;
    byCategory: Record<PitfallCategory, number>;
    bySeverity: Record<'high' | 'medium' | 'low', number>;
  };
}

// ─── QuickstartResult ───

export interface QuickstartResult {
  fiveMinuteOverview: {
    purpose: string;
    techStack: string[];
    coreModules: string[];
    startupCommand: string;
  };
  devSetupSteps: string[];
  businessOverview: BusinessOverviewEntry[];
  warnings: PitfallRecord[];
  apiQuickRef?: ApiQuickRefEntry[];
}

export interface BusinessOverviewEntry {
  moduleName: string;
  description: string;
  keyFiles: string[];
  relatedApis: string[];
}

export interface ApiQuickRefEntry {
  path: string;
  method: HttpMethod;
  description: string;
}

// ─── AiMemoryResult ───

export interface AiMemoryResult {
  memoryData: AiMemoryData;
  jsonFilePath: string;
  markdownFilePath: string;
}
