/**
 * OpsConfig — Ops 分析配置数据模型
 */

export interface OpsConfig {
  /** 反模式检测阈值配置 */
  antiPatternThresholds: {
    maxMethodLines: number;
    maxNestingDepth: number;
    maxClassMethods: number;
    maxClassLines: number;
    maxFileLines: number;
  };
  /** 已知的自动生成目录名 */
  autoGeneratedDirs: string[];
  /** 目录树最大展示深度 */
  maxTreeDepth: number;
}
